#!/usr/bin/env python3

"""
ktr is kentauros.py
"""

from kentauros.init import DEBUG, VERBY, log
from kentauros.config import KTR_CONF
from kentauros.bootstrap import ktr_bootstrap

from kentauros.package import Package


log("ktr: DEBUG set: " + str(DEBUG), 0)
log("ktr: VERBOSITY: " + str(VERBY), 1)

log("ktr: BASEDIR: " + KTR_CONF['main']['basedir'], 1)
log("ktr: CONFDIR: " + KTR_CONF['main']['confdir'], 1)
log("ktr: DATADIR: " + KTR_CONF['main']['datadir'], 1)
log("ktr: SPECDIR: " + KTR_CONF['main']['specdir'], 1)

ktr_bootstrap()

# initialise mesa package, read $KTR_CONFDIR/mesa.conf
MESA_PKG = Package("mesa")

# prepare mesa sources
MESA_PKG.source.get()
MESA_PKG.source.update()
MESA_PKG.source.export()

# construct mesa-VERSION.src.rpm
MESA_PKG.constructor.init()
MESA_PKG.constructor.prepare()
MESA_PKG.constructor.build()
MESA_PKG.constructor.export()
MESA_PKG.constructor.clean()

# upload package to copr if mock build is successful
if MESA_PKG.builder.build():
    MESA_PKG.uploader.upload()

