#!/usr/bin/env python3

"""
ktr is kentauros.py
"""

from kentauros.init import DEBUG, VERBY, log
from kentauros.config import KTR_CONF
from kentauros.bootstrap import ktr_bootstrap

from kentauros.package import Package


log("DEBUG set: " + str(DEBUG), 1)
log("VERBOSITY: " + str(VERBY), 1)

log("BASEDIR: " + KTR_CONF['main']['basedir'], 1)
log("CONFDIR: " + KTR_CONF['main']['confdir'], 1)
log("DATADIR: " + KTR_CONF['main']['datadir'], 1)
log("SPECDIR: " + KTR_CONF['main']['specdir'], 1)

ktr_bootstrap()

mesa_package = Package("mesa")

mesa_package.source.get()
mesa_package.source.update()
mesa_package.source.export()

