#!/usr/bin/env python3

"""ktr-create is kentauros-create.py
This simple python script is only included in git for testing purposes. A script
like this will be generated at install time by setuptools, using the specified
entry point :py:func:`kentauros.run.ktr_create.run_create`.
"""


# pylint: disable=invalid-name

from kentauros.run.ktr_create import run_create

run_create()

