#!/usr/bin/env python3

"""ktr-config is kentauros-config.py
This simple python script is only included in git for testing purposes. A script
like this will be generated at install time by setuptools, using the specified
entry point :py:func:`kentauros.run.ktr_config.run_config`.
"""


# pylint: disable=invalid-name


import os
import sys

sys.path.insert(0, os.getcwd())

from kentauros.run.ktr_config import run_config

run_config()

