#!/usr/bin/env python3

# PYTHON_ARGCOMPLETE_OK

"""ktr is kentauros.py
This script launches kentauros by executing the appropriate function as entry point.
"""


import sys

from kentauros.run import run

sys.exit(run())
